name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'  # Adjust the tag pattern as needed
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build and package Electron app for Linux
        run: pnpm build --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install
      
      - name: Install Wine and Mono
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y --install-recommends wine64 wine32 mono-complete

      - name: Build and package Electron app for Windows
        run: pnpm build --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build and package Electron app for macOS
        run: pnpm build --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
