name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'  # Adjust the tag pattern as needed
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: win
          - os: macos-latest
            target: mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build and package Electron app
        run: pnpx electron-builder --${{ matrix.target }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
